# -*- coding: utf-8 -*-
"""Untitled5.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1fpB-2vlgfEwFKKyAixurR4l78VG55fJM
"""

import streamlit as st
 
def add(a, b):
  return a + b
 
st.title("Calculator App using Streamlit")
 
# creates a horizontal line
st.write("---")
# input 1
a = st.number_input(label="Enter first number")
 
# input 2
b = st.number_input(label="Enter second number")
st.write(add(a,b))

if st.button("Calculate result"):
    add()